# Generated by Django 5.1 on 2024-09-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('SELLER', 'Seller'), ('CUSTOMER', 'Customer')], default='SELLER', max_length=20),
        ),
    ]
