# Generated by Django 5.1 on 2024-09-09 02:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0002_alter_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('payment_method', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MASTERCARD')], max_length=20, null=True)),
                ('credit_card_number', models.CharField(max_length=100)),
                ('credit_card_holder', models.CharField(max_length=200)),
                ('order_status', models.CharField(choices=[('DRAFTED', 'Draft'), ('CREATED', 'Create'), ('SUCCESS', 'Success')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.product')),
            ],
        ),
    ]
